### PR TITLE
Create Command_ifm.java

### PR DESCRIPTION
**Pull request by DarkGamingDronze**
This would be very effective and helpful for the operators to know what kind of FreedomMod this is

### CODE REVIEW

**Comment by aggelosQQ** [comment]
```TFM_Util.playerMsg(sender_p, "§5Made in the image of the §9TotalFreedomMod §5but with more §6features §5and §eflexibility.", ChatColor.GOLD);```
Why do you need ```ChatColo.GOLD``` if you are going to use color codes?

**Comment by LegendIsAwesomes** [comment]
There are several issues with this PR. 

For one it's in the old TFM, We currently use TFM 5.0, update it please.
It doesn't compile.

**Comment by DarkGamingDronze** [comment]
It does compile for me.


Fixing in progress.

**Comment by DarkGamingDronze** [comment]
Updated to TFM 5.0

**Comment by LegendIsAwesomes** [comment]
Still doesn't compile, would also break the licence.

**Comment by DarkGamingDronze** [comment]
Can't seem to find the problem..
I need some help.

**Comment by DarkGamingDronze** [comment]
Sorry guys, i let you down... i don't fit to be a developer anymore.. seems that i lost that magical touch

I am gonna close this, i still allow you to use the codes.

**Comment by LegendIsAwesomes** [comment]
Study TFM 5.0 before making anymore PR's please.

**Pull request closed without merging**
